
name: CI

on:
  push:
    branches: [ "main" , "pruebaA" ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: "Display message"
        run: echo "Hello, world!"
